/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p_Gra;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.Arrays;
import java.util.Collections;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;


@Singleton
public class Gra extends javax.swing.JFrame {
    
	private static Gra instance = null;
    String zestaw;
    String imie = new String();
    OutPytan latwe = new OutPytan();
    OutPytan srednie = new OutPytan();
    OutPytan trudne = new OutPytan();
    AddStatsPytan statystyki = new AddStatsPytan();
    SaveGry  Stangry = new SaveGry();
    int polnapol = 0;
    int pub = 0;
    int friend = 0;
    int rezygnacja = 0;
    int czywczytac = 0;
    int minusdlastatystyki = 0;
   
    int licznik=1;
    /**
     * Creates new form Gra
     * @throws IOException 
     */
    
    public static Gra getInstance(String imie, String zestaw, int czywczytac) throws IOException {
        if(instance == null) {
           instance = new Gra(imie,zestaw,czywczytac);
        }
        return instance;
     }
    public Gra() {
        initComponents();
    }

    protected Gra (String imie, String zestaw, int czywczytac) throws IOException {
       initComponents();
       this.czywczytac = czywczytac;
       this.imie = imie;
       this.zestaw = zestaw;
       this.Imie_Gracza.setText(imie);
       this.getContentPane().setBackground(Color.black);
       latwe.WyborZestawu(zestaw);
       latwe.WczytajPytania("1");
       
       if(this.czywczytac == 1)
       {
    	   Stangry.ustaw();
    	   this.polnapol = Stangry.polnapol;
    	   this.pub = Stangry.pub;
    	   this.friend = Stangry.friend;
    	   System.out.print(Stangry.friend);
    	   if(polnapol==1)
    		   	polnapolLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazki/1X.png")));    
    	   if(friend==1)
    		   	TelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazki/2X.png")));
    	   if(pub==1)
    		   PubLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazki/3X.png")));
    	   this.minusdlastatystyki = 1;
    	   licznik = Stangry.licznik;
    	   licznik = licznik - 1;
       
    	   if(licznik >=1 && licznik <=5)
    	   {
    		   latwe.WyborZestawu(zestaw);
    		   latwe.WczytajPytania("1");
    		   latwe.pom = Stangry.pom;
    		   for(int i =0; i<5; i++)
    			   latwe.tabpom[i] = Stangry.tabpom[i];
    	   }

    	   if(licznik >= 6 && licznik <=10)
    	   {
    		   srednie.WyborZestawu(zestaw);
    		   srednie.WczytajPytania("2");
    		   latwe = srednie;    
    		   latwe.pom = Stangry.pom;
    		   for(int i =0; i<5; i++)
    			   latwe.tabpom[i] = Stangry.tabpom[i];
    		   this.czywczytac = 2;
    	   }
       
    	    if(licznik >=11 && licznik <=15 )
    	   	{
    		   trudne.WyborZestawu(zestaw);
    		   trudne.WczytajPytania("3");
    		   latwe = trudne;
    		   latwe.pom = Stangry.pom;
    		   for(int i =0; i<5; i++)
    			   latwe.tabpom[i] = Stangry.tabpom[i];
    		   this.czywczytac = 3;
    	   	}
       }
       
       statystyki.Wyborzestawu(zestaw);
       Obsluga();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void Obsluga() throws IOException
    {
        
        String [] labelwygranych = {"/Obrazki/hajsy.png", "/Obrazki/hajsy2.png", "/Obrazki/hajsy3.png", "/Obrazki/hajsy4.png", "/Obrazki/hajsy5.png"  
        , "/Obrazki/hajsy6.png", "/Obrazki/hajsy7.png", "/Obrazki/hajsy8.png", "/Obrazki/hajsy9.png", "/Obrazki/hajsy10.png", "/Obrazki/hajsy11.png"
        , "/Obrazki/hajsy12.png", "/Obrazki/hajsy13.png", "/Obrazki/hajsy14.png", "/Obrazki/hajsy15.png"};
         
       
       
       
       if(licznik==6)
       {
    	   srednie.WyborZestawu(zestaw);
    	   if(czywczytac==2)
    		   srednie.pom = Stangry.pom;
    	   else
    		   srednie.WczytajPytania("2");
    	   latwe = srednie;
       }
       
       if(licznik==11)
       {
    	   trudne.WyborZestawu(zestaw);
    	   if(czywczytac==3)
    		   trudne.pom = Stangry.pom;
    	   else
    		   trudne.WczytajPytania("3");
    	   latwe = trudne;
       }
        
       
      
       if(licznik==16)
           {
               
               this.setVisible(false);
               licznik++; 
               this.podsumowanie_dialog.setVisible(true);
               
           }
       else
       {
       
       if(this.minusdlastatystyki == 1)
       {
          this.minusdlastatystyki = 0;
           
       }
       else
           statystyki.ustawiloscpytan(latwe.ZadajPytanie());
       
       Hajsy.setIcon(new javax.swing.ImageIcon(getClass().getResource(labelwygranych[(licznik-1)])));
       pytanieLabel.setText(latwe.ZadajPytanie());
       
       ODPA.setVisible(true);
       ODPB.setVisible(true);
       ODPC.setVisible(true);
       ODPD.setVisible(true);
       
       ODPA.setText(latwe.Wczytaja());
       ODPB.setText(latwe.Wczytajb());
       ODPC.setText(latwe.Wczytajc());
       ODPD.setText(latwe.Wczytajd());
       
       licznik++; 
       }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        podsumowanie_dialog = new javax.swing.JDialog();
        podsumowanie_txt = new javax.swing.JLabel();
        dalej_button = new javax.swing.JButton();
        podsumowanie_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        publika = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        publikaLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        przyjaciel = new javax.swing.JDialog();
        jButton2 = new javax.swing.JButton();
        przyjacielLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Imie_Gracza = new javax.swing.JLabel();
        WitajLabel = new javax.swing.JLabel();
        Hajsy = new javax.swing.JLabel();
        polnapolLabel = new javax.swing.JLabel();
        TelLabel = new javax.swing.JLabel();
        PubLabel = new javax.swing.JLabel();
        ZapiszButton = new javax.swing.JButton();
        RezygnujeButton = new javax.swing.JButton();
        ODPC = new javax.swing.JLabel();
        ODPB = new javax.swing.JLabel();
        ODPD = new javax.swing.JLabel();
        ODPA = new javax.swing.JLabel();
        pytanieLabel = new javax.swing.JLabel();
        TLO = new javax.swing.JLabel();

        podsumowanie_dialog.setLocation(new java.awt.Point(750, 380));
        podsumowanie_dialog.setMinimumSize(new java.awt.Dimension(648, 432));
        podsumowanie_dialog.setResizable(false);
        podsumowanie_dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                podsumowanie_dialogWindowOpened(evt);
            }
        });

        podsumowanie_txt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        podsumowanie_txt.setForeground(new java.awt.Color(255, 0, 51));
        podsumowanie_txt.setText("Koniec gry, dzieki!");

        dalej_button.setText("Dalej");
        dalej_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dalej_buttonMouseClicked(evt);
            }
        });

        podsumowanie_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        podsumowanie_label.setForeground(new java.awt.Color(255, 255, 255));
        podsumowanie_label.setText("jLabel1");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazki/logo2.png"))); // NOI18N
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout podsumowanie_dialogLayout = new javax.swing.GroupLayout(podsumowanie_dialog.getContentPane());
        podsumowanie_dialog.getContentPane().setLayout(podsumowanie_dialogLayout);
        podsumowanie_dialogLayout.setHorizontalGroup(
            podsumowanie_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, podsumowanie_dialogLayout.createSequentialGroup()
                .addGap(0, 210, Short.MAX_VALUE)
                .addComponent(podsumowanie_txt)
                .addGap(76, 76, 76)
                .addComponent(jLabel3))
            .addGroup(podsumowanie_dialogLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(dalej_button, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(podsumowanie_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(podsumowanie_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        podsumowanie_dialogLayout.setVerticalGroup(
            podsumowanie_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(podsumowanie_dialogLayout.createSequentialGroup()
                .addGroup(podsumowanie_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(podsumowanie_dialogLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(podsumowanie_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(podsumowanie_label, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(dalej_button, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        publika.setLocation(new java.awt.Point(750, 380));
        publika.setMinimumSize(new java.awt.Dimension(400, 320));
        publika.setModal(true);
        publika.setResizable(false);
        publika.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                publikaWindowOpened(evt);
            }
        });

        jButton1.setText("Powrot do gry");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        publikaLabel.setForeground(new java.awt.Color(255, 255, 255));
        publikaLabel.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazki/logo2.png"))); // NOI18N

        javax.swing.GroupLayout publikaLayout = new javax.swing.GroupLayout(publika.getContentPane());
        publika.getContentPane().setLayout(publikaLayout);
        publikaLayout.setHorizontalGroup(
            publikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publikaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(publikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(publikaLayout.createSequentialGroup()
                        .addComponent(publikaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, publikaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(publikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, publikaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(111, 111, 111))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, publikaLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(146, 146, 146))))))
        );
        publikaLayout.setVerticalGroup(
            publikaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, publikaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(publikaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(83, 83, 83))
        );

        przyjaciel.setLocation(new java.awt.Point(750, 380));
        przyjaciel.setMinimumSize(new java.awt.Dimension(400, 320));
        przyjaciel.setResizable(false);
        przyjaciel.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                przyjacielWindowOpened(evt);
            }
        });

        jButton2.setText("Powrot do gry");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        przyjacielLabel.setForeground(new java.awt.Color(255, 255, 255));
        przyjacielLabel.setText("jLabel1");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazki/logo2.png"))); // NOI18N

        javax.swing.GroupLayout przyjacielLayout = new javax.swing.GroupLayout(przyjaciel.getContentPane());
        przyjaciel.getContentPane().setLayout(przyjacielLayout);
        przyjacielLayout.setHorizontalGroup(
            przyjacielLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, przyjacielLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(przyjacielLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, przyjacielLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, przyjacielLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(143, 143, 143))))
            .addComponent(przyjacielLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        przyjacielLayout.setVerticalGroup(
            przyjacielLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(przyjacielLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(przyjacielLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(34, 34, 34))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazki/logo.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(600, 200));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(850, 740));
        setPreferredSize(new java.awt.Dimension(850, 740));
        setResizable(false);
        getContentPane().setLayout(null);

        Imie_Gracza.setForeground(new java.awt.Color(255, 255, 255));
        Imie_Gracza.setText("Imie gracza");
        getContentPane().add(Imie_Gracza);
        Imie_Gracza.setBounds(270, 260, 55, 14);

        WitajLabel.setBackground(new java.awt.Color(255, 255, 255));
        WitajLabel.setForeground(new java.awt.Color(255, 255, 255));
        WitajLabel.setText("Witaj");
        getContentPane().add(WitajLabel);
        WitajLabel.setBounds(240, 240, 40, 14);

        Hajsy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazki/hajsy.png"))); // NOI18N
        getContentPane().add(Hajsy);
        Hajsy.setBounds(560, 70, 280, 550);

        polnapolLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazki/1.png"))); // NOI18N
        polnapolLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                polnapolLabelMouseClicked(evt);
            }
        });
        getContentPane().add(polnapolLabel);
        polnapolLabel.setBounds(650, 50, 104, 55);

        TelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazki/2.png"))); // NOI18N
        TelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TelLabelMouseClicked(evt);
            }
        });
        getContentPane().add(TelLabel);
        TelLabel.setBounds(720, 0, 112, 56);

        PubLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazki/3.png"))); // NOI18N
        PubLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PubLabelMouseClicked(evt);
            }
        });
        getContentPane().add(PubLabel);
        PubLabel.setBounds(560, 0, 104, 54);

        ZapiszButton.setText("Zapisz");
        ZapiszButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ZapiszButtonMousePressed(evt);
            }
        });
        getContentPane().add(ZapiszButton);
        ZapiszButton.setBounds(580, 600, 110, 50);

        RezygnujeButton.setText("Rezygnuje");
        RezygnujeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RezygnujeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(RezygnujeButton);
        RezygnujeButton.setBounds(710, 600, 110, 50);

        ODPC.setForeground(new java.awt.Color(255, 255, 255));
        ODPC.setText("C");
        ODPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ODPCMouseClicked(evt);
            }
        });
        getContentPane().add(ODPC);
        ODPC.setBounds(20, 630, 240, 50);

        ODPB.setForeground(new java.awt.Color(255, 255, 255));
        ODPB.setText("B");
        ODPB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ODPBMouseClicked(evt);
            }
        });
        getContentPane().add(ODPB);
        ODPB.setBounds(300, 570, 240, 50);

        ODPD.setForeground(new java.awt.Color(255, 255, 255));
        ODPD.setText("D");
        ODPD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ODPDMouseClicked(evt);
            }
        });
        getContentPane().add(ODPD);
        ODPD.setBounds(300, 630, 240, 50);

        ODPA.setForeground(new java.awt.Color(255, 255, 255));
        ODPA.setText("A");
        ODPA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ODPAMouseClicked(evt);
            }
        });
        getContentPane().add(ODPA);
        ODPA.setBounds(24, 574, 230, 40);

        pytanieLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pytanieLabel.setForeground(new java.awt.Color(255, 255, 255));
        pytanieLabel.setText("Pytanie");
        getContentPane().add(pytanieLabel);
        pytanieLabel.setBounds(80, 470, 400, 60);

        TLO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazki/Frontpage.png"))); // NOI18N
        getContentPane().add(TLO);
        TLO.setBounds(0, -10, 560, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RezygnujeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RezygnujeButtonMouseClicked
        this.setVisible(false);
        rezygnacja = 1;
        this.podsumowanie_dialog.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_RezygnujeButtonMouseClicked

    private void ODPAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ODPAMouseClicked
       
    	SprawdzOdpFacade odp = new SprawdzOdpFacade(latwe.Wczytaja(),latwe.Wczytajpop());
    	int wynik=0;
    	wynik = odp.getValue();
    	if(wynik==1)
       {
    	   
           
       try {
           statystyki.ustawiloscodp(2, latwe.ZadajPytanie());
           
            latwe.ods();
           Obsluga();
          
       } catch (IOException ex) {
           Logger.getLogger(Gra.class.getName()).log(Level.SEVERE, null, ex);
       }
       }
       else
       {
           try {
               
               try {
                   statystyki.ustawiloscodp(1, latwe.ZadajPytanie());
               } catch (UnsupportedEncodingException ex) {
                   Logger.getLogger(Gra.class.getName()).log(Level.SEVERE, null, ex);
               }
                this.setVisible(false);
               this.podsumowanie_dialog.setVisible(true);
           } catch (FileNotFoundException ex) {
               Logger.getLogger(Gra.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }//GEN-LAST:event_ODPAMouseClicked

    private void ODPBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ODPBMouseClicked
         
    	SprawdzOdpFacade odp = new SprawdzOdpFacade(latwe.Wczytajb(),latwe.Wczytajpop());
    	int wynik=0;
    	wynik = odp.getValue();
        if(wynik ==1)
       {
       try {
           statystyki.ustawiloscodp(2, latwe.ZadajPytanie());
            latwe.ods();
           Obsluga();
           
       } catch (IOException ex) {
           Logger.getLogger(Gra.class.getName()).log(Level.SEVERE, null, ex);
       }
       }
        else
       {
           try {
               
               statystyki.ustawiloscodp(1, latwe.ZadajPytanie());
                this.setVisible(false);
               this.podsumowanie_dialog.setVisible(true);
           } catch (FileNotFoundException ex) {
               Logger.getLogger(Gra.class.getName()).log(Level.SEVERE, null, ex);
           } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(Gra.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
    }//GEN-LAST:event_ODPBMouseClicked

    private void ODPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ODPCMouseClicked
       
    	SprawdzOdpFacade odp = new SprawdzOdpFacade(latwe.Wczytajc(),latwe.Wczytajpop());
    	int wynik=0;
    	wynik = odp.getValue();
        if(wynik ==1)
       {
       try {
           statystyki.ustawiloscodp(2, latwe.ZadajPytanie());
           
           latwe.ods();
           Obsluga();
           
       } catch (IOException ex) {
           Logger.getLogger(Gra.class.getName()).log(Level.SEVERE, null, ex);
       }
       }
        else
       {
           try {
               
               statystyki.ustawiloscodp(1, latwe.ZadajPytanie());
                this.setVisible(false);
               this.podsumowanie_dialog.setVisible(true);
           } catch (FileNotFoundException ex) {
               Logger.getLogger(Gra.class.getName()).log(Level.SEVERE, null, ex);
           } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(Gra.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
    }//GEN-LAST:event_ODPCMouseClicked

    private void ODPDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ODPDMouseClicked
    	SprawdzOdpFacade odp = new SprawdzOdpFacade(latwe.Wczytajd(),latwe.Wczytajpop());
    	int wynik=0;
    	wynik = odp.getValue();
        if(wynik ==1)
       {
       try {
           statystyki.ustawiloscodp(2, latwe.ZadajPytanie());
          
           latwe.ods();
           Obsluga();
           
       } catch (IOException ex) {
           Logger.getLogger(Gra.class.getName()).log(Level.SEVERE, null, ex);
       }
       }
       else
       {
           try {
               
               statystyki.ustawiloscodp(1, latwe.ZadajPytanie());
               this.setVisible(false);
               this.podsumowanie_dialog.setVisible(true);
           } catch (FileNotFoundException ex) {
               Logger.getLogger(Gra.class.getName()).log(Level.SEVERE, null, ex);
           } catch (UnsupportedEncodingException ex) {
               Logger.getLogger(Gra.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }//GEN-LAST:event_ODPDMouseClicked

    private void polnapolLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_polnapolLabelMouseClicked
        if(polnapol==0)
        {
            polnapolLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazki/1X.png")));
            
            if(latwe.Wczytajpop().equals(latwe.Wczytaja()))
            {
                ODPB.setVisible(false);
                ODPC.setVisible(false);
            }
                
            if(latwe.Wczytajpop().equals(latwe.Wczytajb()))
            {
                ODPA.setVisible(false);
                ODPD.setVisible(false);
            }
            if(latwe.Wczytajpop().equals(latwe.Wczytajc()))
            {
                ODPB.setVisible(false);
                ODPD.setVisible(false);
            }
            
            if(latwe.Wczytajpop().equals(latwe.Wczytajd()))
            {
                ODPB.setVisible(false);
                ODPC.setVisible(false);
            }
            polnapol = 1;
        }
    }//GEN-LAST:event_polnapolLabelMouseClicked

    private void PubLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PubLabelMouseClicked
        if(pub == 0)
        {   
            
            PubLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazki/3X.png")));
       
            pub = 1;
            this.publika.setVisible(true);
            

        }
    }//GEN-LAST:event_PubLabelMouseClicked

    private void publikaWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_publikaWindowOpened
        this.publika.getContentPane().setBackground(Color.black);
        int a = 0, b = 0, c = 0, d = 0;
        int pom;
        
        Random generator = new Random();
        String tab [] = new String [100];
        
        for(int i =0; i<75; i++)
        {
        pom = generator.nextInt(4);
        
        if(pom == 0)
            tab[i] = latwe.Wczytaja();
        if(pom == 1)
            tab[i] = latwe.Wczytajb();
        if(pom == 2)
            tab[i] = latwe.Wczytajc();
        if(pom == 3)
            tab[i] = latwe.Wczytajd();        
        }
        
        for(int i =75; i<100; i++)
            tab[i] = latwe.Wczytajpop();
   
        for(int i = 0; i < 100; i++)
        {
            if(tab[i].equals(latwe.Wczytaja()))
                a++;
            if(tab[i].equals(latwe.Wczytajb()))
                b++;
            if(tab[i].equals(latwe.Wczytajc()))
                c++;
            if(tab[i].equals(latwe.Wczytajd()))
                d++;
            
        }
        
           
      publikaLabel.setText("Zestawienie procentowe: a: " + a +"% b: " + b + "% c: " + c + "% d: " + d + "%");
  
            
    }//GEN-LAST:event_publikaWindowOpened

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    publika.setVisible(false);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void TelLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelLabelMouseClicked
       if(friend == 0)
        {   
            
            TelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazki/2X.png")));
            friend = 1;
            this.przyjaciel.setVisible(true);
            
           
            
        }
        
        
    }//GEN-LAST:event_TelLabelMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
      przyjaciel.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void przyjacielWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_przyjacielWindowOpened
       String tab [] = new String [100];
       this.przyjaciel.getContentPane().setBackground(Color.black);
         if(latwe.Wczytajpop().equals(latwe.Wczytaja()))
         {
           for(int i=0; i<75; i++ )
               tab[i] = latwe.Wczytaja();
            
           for(int i=75; i<83; i++ )
               tab[i] = latwe.Wczytajb();
           
           for(int i=83; i<91; i++ )
               tab[i] = latwe.Wczytajc();
           
           for(int i=91; i<100; i++ )
               tab[i] = latwe.Wczytajd();
         }
         
         
          if(latwe.Wczytajpop().equals(latwe.Wczytajb()))
        {
           for(int i=0; i<75; i++ )
               tab[i] = latwe.Wczytajb();
            
           for(int i=75; i<83; i++ )
               tab[i] = latwe.Wczytaja();
           
           for(int i=83; i<91; i++ )
               tab[i] = latwe.Wczytajc();
           
           for(int i=91; i<100; i++ )
               tab[i] = latwe.Wczytajd();
         }
          
           if(latwe.Wczytajpop().equals(latwe.Wczytajc()))
         {
           for(int i=0; i<75; i++ )
               tab[i] = latwe.Wczytajc();
            
           for(int i=75; i<83; i++ )
               tab[i] = latwe.Wczytajb();
           
           for(int i=83; i<91; i++ )
               tab[i] = latwe.Wczytaja();
           
           for(int i=91; i<100; i++ )
               tab[i] = latwe.Wczytajd();
         }
           
            if(latwe.Wczytajpop().equals(latwe.Wczytajd()))
        {
           for(int i=0; i<75; i++ )
               tab[i] = latwe.Wczytajd();
            
           for(int i=75; i<83; i++ )
               tab[i] = latwe.Wczytajb();
           
           for(int i=83; i<91; i++ )
               tab[i] = latwe.Wczytajc();
           
           for(int i=91; i<100; i++ )
               tab[i] = latwe.Wczytaja();
         }
        
         
             for(int i=1; i<tab.length; i++)
            Collections.shuffle(Arrays.asList(tab));
           
      przyjacielLabel.setText("Przyjaciel podpowiada, ze poprawna odp to: " + tab[0]);
    }//GEN-LAST:event_przyjacielWindowOpened

    private void ZapiszButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZapiszButtonMousePressed
        Menu form2 = new Menu();
        SaveGry  form = new SaveGry();
        try {
            form.zapisz(friend, polnapol, pub, licznik, zestaw, imie, latwe.tabpom, latwe.pom );
            form.ustaw();
            this.setVisible(false);
            form2.setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Gra.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Gra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_ZapiszButtonMousePressed

    private void podsumowanie_dialogWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_podsumowanie_dialogWindowOpened
        int tab [] = {0,100, 200, 500, 1000, 2000, 5000, 10000, 15000, 30000, 50000, 100000, 200000, 400000, 500000, 1000000};
        this.podsumowanie_dialog.getContentPane().setBackground(Color.black);
        if(rezygnacja == 1)
        podsumowanie_label.setText("Odpowiedziales poprawnie na " + (licznik-2) + " pytan, zarabiajac " + tab[licznik-2] + " zl" );
        else
        {
            if((licznik-2) < 5)
            podsumowanie_label.setText("Odpowiedziales poprawnie na " + (licznik-2) + " pytan, zarabiajac " + tab[0] + " zl");

            if((licznik-2) >= 5 && (licznik-2) <= 9)
            podsumowanie_label.setText("Odpowiedziales poprawnie na " + (licznik-2) + " pytan, zarabiajac " + tab[5] + " zl");

            if((licznik-2) >= 10 && (licznik-2) <= 14)
            podsumowanie_label.setText("Odpowiedziales poprawnie na " + (licznik-2) + " pytan, zarabiajac " + tab[10] + " zl");

            if((licznik-2) == 15)
            podsumowanie_label.setText("Odpowiedziales poprawnie na " + (licznik-2) + " pytan, zarabiajac " + tab[15] + " zl");

           

        }
    }//GEN-LAST:event_podsumowanie_dialogWindowOpened

    private void dalej_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dalej_buttonMouseClicked
        this.podsumowanie_dialog.setVisible(false);
        Menu form = new Menu();
        form.setVisible(true);
        AddStatsGracz form2 = new AddStatsGracz(imie, licznik);
        try {
            form2.dodaj_statysytke_gracza();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Gra.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Gra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dalej_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hajsy;
    private javax.swing.JLabel Imie_Gracza;
    private javax.swing.JLabel ODPA;
    private javax.swing.JLabel ODPB;
    private javax.swing.JLabel ODPC;
    private javax.swing.JLabel ODPD;
    private javax.swing.JLabel PubLabel;
    private javax.swing.JButton RezygnujeButton;
    private javax.swing.JLabel TLO;
    private javax.swing.JLabel TelLabel;
    private javax.swing.JLabel WitajLabel;
    private javax.swing.JButton ZapiszButton;
    private javax.swing.JButton dalej_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JDialog podsumowanie_dialog;
    private javax.swing.JLabel podsumowanie_label;
    private javax.swing.JLabel podsumowanie_txt;
    private javax.swing.JLabel polnapolLabel;
    private javax.swing.JDialog przyjaciel;
    private javax.swing.JLabel przyjacielLabel;
    private javax.swing.JDialog publika;
    private javax.swing.JLabel publikaLabel;
    private javax.swing.JLabel pytanieLabel;
    // End of variables declaration//GEN-END:variables
}