/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p_Gra;

import java.awt.event.ActionListener;
import javax.swing.*;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;



public class MenuView extends javax.swing.JFrame {
    
    int wybor;

    /**
     * Creates new form Menu
     */
    public MenuView() {
        initComponents();
        this.UwagaLabel.setVisible(false);
        this.UwagaLabel1.setVisible(false);
        this.getContentPane().setBackground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PytanieImie = new javax.swing.JDialog();
        DalejButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        InfoLabel = new javax.swing.JLabel();
        UwagaLabel = new javax.swing.JLabel();
        InfoLabel1 = new javax.swing.JLabel();
        UwagaLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        PytanieZestaw = new javax.swing.JDialog();
        DalejButton1 = new javax.swing.JButton();
        InfoLabel2 = new javax.swing.JLabel();
        UwagaLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        GrajButton = new javax.swing.JButton();
        WyjscieButton = new javax.swing.JButton();
        LogoGry = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        Opcje = new javax.swing.JMenu();
        EdytorHasel = new javax.swing.JMenuItem();
        OsiagnieciaGraczy = new javax.swing.JMenuItem();
        StatystykiPytan = new javax.swing.JMenuItem();
        WczytajGre = new javax.swing.JMenuItem();

        PytanieImie.setLocation(new java.awt.Point(750, 380));
        PytanieImie.setMinimumSize(new java.awt.Dimension(500, 430));
        PytanieImie.setResizable(false);

        DalejButton.setLabel("Dalej");
        DalejButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DalejButtonMouseClicked(evt);
            }
        });

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        InfoLabel.setForeground(new java.awt.Color(255, 255, 255));
        InfoLabel.setText("WPORWADZ NUMER ZESTAWU (Od 1-3)");

        UwagaLabel.setForeground(new java.awt.Color(255, 0, 51));
        UwagaLabel.setText("WPORWADZ IMIE");

        InfoLabel1.setForeground(new java.awt.Color(255, 255, 255));
        InfoLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InfoLabel1.setText("Wprowadz imie");

        UwagaLabel1.setForeground(new java.awt.Color(255, 0, 51));
        UwagaLabel1.setText("WPORWADZ NUMER ZESTAWU");

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PytanieImieLayout = new javax.swing.GroupLayout(PytanieImie.getContentPane());
        PytanieImie.getContentPane().setLayout(PytanieImieLayout);
        PytanieImieLayout.setHorizontalGroup(
            PytanieImieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PytanieImieLayout.createSequentialGroup()
                .addGroup(PytanieImieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PytanieImieLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(UwagaLabel))
                    .addGroup(PytanieImieLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(DalejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PytanieImieLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(UwagaLabel1))
                    .addGroup(PytanieImieLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(PytanieImieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(InfoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PytanieImieLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(InfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PytanieImieLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        PytanieImieLayout.setVerticalGroup(
            PytanieImieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PytanieImieLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(InfoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UwagaLabel)
                .addGap(38, 38, 38)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(UwagaLabel1)
                .addGap(53, 53, 53)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(DalejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        PytanieZestaw.setLocation(new java.awt.Point(750, 380));
        PytanieZestaw.setMinimumSize(new java.awt.Dimension(401, 333));
        PytanieZestaw.setResizable(false);
        PytanieZestaw.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                PytanieZestawWindowOpened(evt);
            }
        });

        DalejButton1.setLabel("Dalej");
        DalejButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DalejButton1MouseClicked(evt);
            }
        });

        InfoLabel2.setForeground(new java.awt.Color(255, 255, 255));
        InfoLabel2.setText("WPORWADZ NUMER ZESTAWU (Od 1-3)");

        UwagaLabel3.setForeground(new java.awt.Color(255, 0, 51));
        UwagaLabel3.setText("WPORWADZ NUMER ZESTAWU");

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout PytanieZestawLayout = new javax.swing.GroupLayout(PytanieZestaw.getContentPane());
        PytanieZestaw.getContentPane().setLayout(PytanieZestawLayout);
        PytanieZestawLayout.setHorizontalGroup(
            PytanieZestawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PytanieZestawLayout.createSequentialGroup()
                .addGroup(PytanieZestawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PytanieZestawLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(UwagaLabel3))
                    .addGroup(PytanieZestawLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PytanieZestawLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(DalejButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PytanieZestawLayout.createSequentialGroup()
                .addGap(0, 82, Short.MAX_VALUE)
                .addComponent(InfoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        PytanieZestawLayout.setVerticalGroup(
            PytanieZestawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PytanieZestawLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(InfoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(UwagaLabel3)
                .addGap(46, 46, 46)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(DalejButton1)
                .addGap(53, 53, 53))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(750, 380));
        setMaximumSize(new java.awt.Dimension(417, 425));
        setMinimumSize(new java.awt.Dimension(417, 425));
        setResizable(false);

        GrajButton.setText("GRAJ");
        GrajButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrajButtonMouseClicked(evt);
            }
        });

        WyjscieButton.setText("WYJSCIE");
        WyjscieButton.setPreferredSize(new java.awt.Dimension(59, 23));
        WyjscieButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                WyjscieButtonMouseClicked(evt);
            }
        });

        LogoGry.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LogoGry.setForeground(new java.awt.Color(255, 255, 255));
        LogoGry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoGry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazki/logo.jpg"))); // NOI18N

        Opcje.setText("Opcje");

        EdytorHasel.setText("Edytor Haseł");
        EdytorHasel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdytorHaselActionPerformed(evt);
            }
        });
        Opcje.add(EdytorHasel);

        OsiagnieciaGraczy.setText("Osiagniecia graczy");
        OsiagnieciaGraczy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OsiagnieciaGraczyActionPerformed(evt);
            }
        });
        Opcje.add(OsiagnieciaGraczy);

        StatystykiPytan.setText("Statystyki pytan");
        StatystykiPytan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatystykiPytanActionPerformed(evt);
            }
        });
        Opcje.add(StatystykiPytan);

        WczytajGre.setText("Wczytaj gre");
        WczytajGre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WczytajGreActionPerformed(evt);
            }
        });
        Opcje.add(WczytajGre);

        Menu.add(Opcje);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LogoGry, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GrajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WyjscieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoGry, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GrajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WyjscieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WyjscieButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WyjscieButtonMouseClicked

        System.exit(0);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_WyjscieButtonMouseClicked

    private void GrajButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrajButtonMouseClicked
        
        this.setVisible(false);
    
                
        this.PytanieImie.getContentPane().setBackground(Color.black); //pytanieimie to dialog
        this.PytanieImie.setVisible(true);
        
       
        
        // TODO add your handling code here:
    }//GEN-LAST:event_GrajButtonMouseClicked

    void addDalejListener(ActionListener listenForGoButton){

    		        DalejButton.addActionListener(listenForGoButton);

    		    }
  // sprawdzania czy cokolwiek zostalo wprwoadzone w dialogu pytanieimie
    
    public String getImie()
    {

        
        this.UwagaLabel.setVisible(false);
        this.UwagaLabel1.setVisible(false);
        
        if("".equals(this.jTextField1.getText()) || "".equals(this.jTextField2.getText()))
                {   

                    if("".equals(this.jTextField1.getText()))
                        this.UwagaLabel.setVisible(true);
                    if("".equals(this.jTextField2.getText()))
                        this.UwagaLabel1.setVisible(true);
                    return null;
                }
        else
        {
        this.PytanieImie.setVisible(false);
        //stworzenie form gra z przekazaniem parametru string imie
        
            
        return this.jTextField1.getText();
            
        }
    }
    
    public String getZestaw()
    {

        
        this.UwagaLabel.setVisible(false);
        this.UwagaLabel1.setVisible(false);
        
        if("".equals(this.jTextField1.getText()) || "".equals(this.jTextField2.getText()))
                {   

                    if("".equals(this.jTextField1.getText()))
                        this.UwagaLabel.setVisible(true);
                    if("".equals(this.jTextField2.getText()))
                        this.UwagaLabel1.setVisible(true);
                    return null;
                }
        else
        {
        this.PytanieImie.setVisible(false);
        //stworzenie form gra z przekazaniem parametru string imie
        
            
        return this.jTextField2.getText();
            
        }
    }
    private void DalejButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DalejButtonMouseClicked

        String imie = this.jTextField1.getText();
        String imie2 = new String();
        imie2 = this.jTextField2.getText();
        
        this.UwagaLabel.setVisible(false);
        this.UwagaLabel1.setVisible(false);
        
        if("".equals(this.jTextField1.getText()) || "".equals(this.jTextField2.getText()))
                {   

                    if("".equals(this.jTextField1.getText()))
                        this.UwagaLabel.setVisible(true);
                    if("".equals(this.jTextField2.getText()))
                        this.UwagaLabel1.setVisible(true);
                }
        else
        {
        this.PytanieImie.setVisible(false);
        //stworzenie form gra z przekazaniem parametru string imie
        
            try {
               Gra form = Gra.getInstance(imie,imie2, 0);
               form.setVisible(true);
              
               
               
            } catch (IOException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_DalejButtonMouseClicked
// sprawdzania w dialogu pytanieimie czy zostala wprowadzona jakas litera
    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char c = evt.getKeyChar();
        
        if (!(Character.isAlphabetic(c)) || (Character.isSpaceChar(c)))
    evt.consume();
               
    }//GEN-LAST:event_jTextField1KeyTyped

    private void EdytorHaselActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdytorHaselActionPerformed
        wybor = 1;
        this.setVisible(false);
        this.PytanieZestaw.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_EdytorHaselActionPerformed

    private void OsiagnieciaGraczyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OsiagnieciaGraczyActionPerformed
     this.setVisible(false);
        try {
            WysStatsGraczy form = WysStatsGraczy.getInstance();
            form.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_OsiagnieciaGraczyActionPerformed

    private void StatystykiPytanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatystykiPytanActionPerformed
        wybor = 0;
    this.setVisible(false);
        this.PytanieZestaw.setVisible(true);
    }//GEN-LAST:event_StatystykiPytanActionPerformed

    private void WczytajGreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WczytajGreActionPerformed
     SaveGry form = new SaveGry();
    
        try {
            if (form.ustaw() == true)
            {
                Gra form2 = new Gra(form.imie, form.zestaw, 1);
                this.setVisible(false);
                form2.setVisible(true);
            }
                
                } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_WczytajGreActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
       
     
        char c = evt.getKeyChar();
        if (!(c=='1' || c=='2' || c=='3'))
        {   
             evt.consume();
             }
        else
        {
            if (jTextField2.getText().length()>0) {
           
            evt.consume();
        }
        
            
        }
    
    }//GEN-LAST:event_jTextField2KeyTyped

    private void DalejButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DalejButton1MouseClicked
        
        String zestaw;
        zestaw = this.jTextField4.getText();
        
        this.UwagaLabel3.setVisible(false);
        
        if("".equals(zestaw))
                        this.UwagaLabel3.setVisible(true);
        else
        {
        this.PytanieZestaw.setVisible(false);
        //stworzenie form gra z przekazaniem parametru string imie
        
            try {
                WysStatsPytan form = new WysStatsPytan(zestaw);
                EdycjaHasel form2 = new EdycjaHasel(zestaw);
                this.setVisible(false);
               if(wybor ==0)
                   form.setVisible(true);
               if(wybor ==1)
                 form2.setVisible(true);
            
               
               
            } catch (IOException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }  
    }//GEN-LAST:event_DalejButton1MouseClicked

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        
         char c = evt.getKeyChar();
        if (!(c=='1' || c=='2' || c=='3'))
        {   
             evt.consume();
             }
        else
        {
            if (jTextField4.getText().length()>0) {
           
            evt.consume();
        }
        
            
        }
        
        
    }//GEN-LAST:event_jTextField4KeyTyped

    private void PytanieZestawWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_PytanieZestawWindowOpened
        this.PytanieZestaw.getContentPane().setBackground(Color.black);    
         this.UwagaLabel3.setVisible(false);
    }//GEN-LAST:event_PytanieZestawWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DalejButton;
    private javax.swing.JButton DalejButton1;
    private javax.swing.JMenuItem EdytorHasel;
    private javax.swing.JButton GrajButton;
    private javax.swing.JLabel InfoLabel;
    private javax.swing.JLabel InfoLabel1;
    private javax.swing.JLabel InfoLabel2;
    private javax.swing.JLabel LogoGry;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu Opcje;
    private javax.swing.JMenuItem OsiagnieciaGraczy;
    private javax.swing.JDialog PytanieImie;
    private javax.swing.JDialog PytanieZestaw;
    private javax.swing.JMenuItem StatystykiPytan;
    private javax.swing.JLabel UwagaLabel;
    private javax.swing.JLabel UwagaLabel1;
    private javax.swing.JLabel UwagaLabel3;
    private javax.swing.JMenuItem WczytajGre;
    private javax.swing.JButton WyjscieButton;
    javax.swing.JTextField jTextField1;
    javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
