/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p_Gra;


import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;



public class WysStatsPytan extends javax.swing.JFrame {

        String [] tabiloscwyswietlen = new String [15];
        String [] tabpop = new String [15];
        String [] tabniepop = new String [15];
        String [] tabpytania = new String [15];
        File file4 = new File("");
        File file = new File("");
        File file2 = new File("");
        File file3 = new File("");
        
    WysStatsPytan(String zestaw) throws FileNotFoundException, IOException {
        
        initComponents();
        
        if("1".equals(zestaw))
                {
         file = new File("src/statystyki/zestaw1.txt");
         file2 = new File("src/statystyki/1_POP.txt");
         file3 = new File("src/statystyki/1_NIEPOP.txt");
         file4 = new File("src/pytania/zestaw1.txt");
 
                }
         if("2".equals(zestaw))
                {
          file = new File("src/statystyki/zestaw2.txt");
         file2 = new File("src/statystyki/2_POP.txt");
         file3 = new File("src/statystyki/2_NIEPOP.txt");
         file4 = new File("src/pytania/zestaw2.txt");
 
                }
          if("3".equals(zestaw))
                {
          file = new File("src/statystyki/zestaw3.txt");
         file2 = new File("src/statystyki/3_POP.txt");
         file3 = new File("src/statystyki/3_NIEPOP.txt");
         file4 = new File("src/pytania/zestaw3.txt");
 
                }
        
        Scanner odczyt5 = new Scanner((file4), "windows-1250");

          odczyt5.nextLine();
            for(int i=0;i<15;i++)
                for(int j=0; j<7; j++)
                {
                    if(j==1)
                    {
                       tabpytania[i] = odczyt5.nextLine();
                    }
                    else
                    {

                        odczyt5.nextLine();
                    }
                }
        FileReader odczyt = new FileReader(file);
        BufferedReader odczytbuff = new BufferedReader(odczyt);
 
        odczytbuff.readLine();
        for(int i=0;i<15;i++)
               tabiloscwyswietlen[i] = odczytbuff.readLine();
        
        FileReader odczyt2 = new FileReader(file2);
        BufferedReader odczytpop = new BufferedReader(odczyt2);
        
        odczytpop.readLine();
        
        for(int i=0;i<15;i++)
               tabpop[i] = odczytpop.readLine();
        
        FileReader odczyt3 = new FileReader(file3);
        BufferedReader odczytniepop = new BufferedReader(odczyt3);
        odczytniepop.readLine();
        
        for(int i=0;i<15;i++)
               tabniepop[i] = odczytniepop.readLine();
        
        
    }

    private WysStatsPytan() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        powrot = new javax.swing.JButton();
        pytania = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        txtwybierznumer = new javax.swing.JLabel();
        txtilerazy = new javax.swing.JLabel();
        txtiloscpoprawnych = new javax.swing.JLabel();
        txtiloscniepop = new javax.swing.JLabel();
        ilosczadanych = new javax.swing.JLabel();
        iloscpoprawnych = new javax.swing.JLabel();
        iloscniepop = new javax.swing.JLabel();
        pytanie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(750, 380));
        setMaximumSize(new java.awt.Dimension(554, 300));
        setMinimumSize(new java.awt.Dimension(554, 300));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        powrot.setText("Powrot do menu");
        powrot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                powrotMouseClicked(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pytanie 1", "Pytanie 2", "Pytanie 3", "Pytanie 4", "Pytanie 5", "Pytanie 6", "Pytanie 7", "Pytanie 8", "Pytanie 9", "Pytanie 10", "Pytanie 11", "Pytanie 12", "Pytanie 13", "Pytanie 14", "Pytanie 15" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        pytania.setViewportView(jList1);

        txtwybierznumer.setForeground(new java.awt.Color(255, 255, 255));
        txtwybierznumer.setText("Wybierz numer pytania z listy");

        txtilerazy.setForeground(new java.awt.Color(255, 255, 255));
        txtilerazy.setText("Ile razy pytanie zostało zadane:");

        txtiloscpoprawnych.setForeground(new java.awt.Color(255, 255, 255));
        txtiloscpoprawnych.setText("Ilosc poprawnych odp:");

        txtiloscniepop.setForeground(new java.awt.Color(255, 255, 255));
        txtiloscniepop.setText("Ilosc nieprawidlowych odp:");

        ilosczadanych.setForeground(new java.awt.Color(255, 255, 255));

        iloscpoprawnych.setForeground(new java.awt.Color(255, 255, 255));

        iloscniepop.setForeground(new java.awt.Color(255, 255, 255));

        pytanie.setForeground(new java.awt.Color(255, 255, 255));
        pytanie.setText("Czekam na wybór pytania z listy ;)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(txtwybierznumer, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pytanie, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pytania, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtilerazy)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(powrot)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtiloscpoprawnych)
                        .addGap(27, 27, 27)
                        .addComponent(txtiloscniepop)))
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(ilosczadanych)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iloscpoprawnych)
                .addGap(147, 147, 147)
                .addComponent(iloscniepop)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtwybierznumer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pytanie, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pytania, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtiloscpoprawnych)
                    .addComponent(txtiloscniepop)
                    .addComponent(txtilerazy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iloscpoprawnych)
                    .addComponent(iloscniepop)
                    .addComponent(ilosczadanych))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(powrot)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked

       int i = 0;

       i = jList1.getSelectedIndex();
       
       ilosczadanych.setText(tabiloscwyswietlen[i]);
       iloscpoprawnych.setText(tabpop[i]);
       iloscniepop.setText(tabniepop[i]);
       pytanie.setText(tabpytania[i]);


    }//GEN-LAST:event_jList1MouseClicked

    private void powrotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_powrotMouseClicked
            Menu form = new Menu();
            this.setVisible(false);
            form.setVisible(true);   
    }//GEN-LAST:event_powrotMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            this.getContentPane().setBackground(Color.black);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WysStatsPytan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WysStatsPytan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WysStatsPytan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WysStatsPytan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WysStatsPytan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iloscniepop;
    private javax.swing.JLabel iloscpoprawnych;
    private javax.swing.JLabel ilosczadanych;
    private javax.swing.JList<String> jList1;
    private javax.swing.JButton powrot;
    private javax.swing.JScrollPane pytania;
    private javax.swing.JLabel pytanie;
    private javax.swing.JLabel txtilerazy;
    private javax.swing.JLabel txtiloscniepop;
    private javax.swing.JLabel txtiloscpoprawnych;
    private javax.swing.JLabel txtwybierznumer;
    // End of variables declaration//GEN-END:variables
}
